#!/usr/bin/env python3
"""Refresh poster assets from the consolidated gic/output runs.

Single source of truth: re-run experiments -> `python refresh.py` -> recompile.
It does two things:
  1. copies the chosen result figures into poster/figures/ under stable names
  2. extracts scalar numbers from each run's result.json into
     poster/generated/results.tex as letter-only \newcommand macros

Only IMAGE-LOSS runs back the main claims; trajectory-loss runs (multiobs /
efield / joint_E_F0) are oracle and live in the clearly-labelled extensions.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
GIC = Path("/home/course/select/b10401006/tmp2/ev-project/gic/output")
TEL = GIC / "ours_telephone"
EXPLORE = REPO / "outputs" / "explore"   # F0 forward+FD analysis (synthetic)

FIG_DIR = HERE / "figures"
GEN_DIR = HERE / "generated"

# (run_dir, {src_filename: dest_stem}) -- dest gets the source suffix
FIGURES: list[tuple[Path, dict[str, str]]] = [
    (TEL / "img_fit_rgb", {"panel_lastframe.png": "fit_rgb_panel",
                           "loss_phys.png": "fit_rgb_loss"}),
    (TEL / "imgjoint_initE4", {"panel_lastframe.png": "sv_fail_panel",
                               "loss_phys.png": "sv_fail_loss"}),
    (TEL / "imgjoint_initE4_mv_front_side", {"panel_lastframe.png": "mv_panel",
                                             "v0_traj.png": "mv_v0",
                                             "loss_phys.png": "mv_loss"}),
    (TEL / "imgfield_bend_diag45", {"field_proj.png": "field_bend_proj",
                                    "grid_quiver.png": "field_bend_quiver",
                                    "panel_lastframe.png": "field_bend_panel"}),
    # extension (trajectory-supervised, oracle)
    (GIC / "ours_multiobs/m0_xpym_initE4", {"E_traj.png": "ext_multiobs"}),
    # Pillar B: excitation channels & F0 (warp forward + finite-difference, synthetic)
    (EXPLORE / "f0_loss_landscape/rel_drop", {"landscape_release.png": "f0_chan_release",
                                              "landscape_drop.png": "f0_chan_drop"}),
    (EXPLORE / "f0_block_freqloss/block_freqloss_gt4p5",
        {"signals_and_spectra.png": "f0_signals"}),
    (EXPLORE / "f0_spectral_K_probe/release_Kprobe_hi", {"period_vs_E.png": "f0_period"}),
    (EXPLORE / "f0_train_S/globalS_run", {"S_recovery.png": "f0_S_recovery"}),
    (EXPLORE / "f0_train_ufield/coarse_bend", {"theta_recovery.png": "f0_field_recovery"}),
    # Results 1: released from a deformed state (F0)
    (EXPLORE / "f0_fit_case/exp1_release_spectral_init475",
        {"forward_panel.png": "f0_released_panel", "F0_stretch.png": "f0_stretch"}),
    (EXPLORE / "f0_gradu_viz/ybend_halfsine",
        {"bend_panel.png": "f0_bend_panel", "deflection.png": "f0_deflection"}),
    # Results 2: inhomogeneous v0 / material fields
    (TEL / "imgfield_mid_side", {"grid_quiver.png": "imgfield_mid_quiver"}),
    (TEL / "imgfield_bend_diag45", {"profile_1d.png": "imgfield_profile"}),
    (GIC / "ours_efield/efdbl_rampE_bend", {"E_grid.png": "efield_E", "E_proj.png": "efield_E_proj"}),
    # Analysis: spectral loss
    (EXPLORE / "f0_spectral_K_probe/release_Kprobe_hi", {"spectra_perK.png": "f0_spectra"}),
]


def copy_figures() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    for run, mapping in FIGURES:
        for src_name, dest_stem in mapping.items():
            src = run / src_name
            dst = FIG_DIR / (dest_stem + Path(src_name).suffix)
            if src.exists():
                shutil.copy2(src, dst)
            else:
                print(f"[warn] missing figure: {src}")


def load(run: str) -> dict:
    p = TEL / run / "result.json"
    if not p.exists():
        p = GIC / run / "result.json"
    return json.loads(p.read_text())


def macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def pct(x: float, nd: int = 2) -> str:
    return f"{abs(x) * 100:.{nd}f}"


def build_macros() -> str:
    out = ["% AUTO-GENERATED by refresh.py -- do not edit by hand\n"]

    fit = load("img_fit_rgb")
    out += [
        macro("GTlogE", f"{fit['gt']['logE']:.0f}"),
        macro("fitRgbErr", pct(fit["rel_err_E"])),
        macro("fitRgbInitLogE", f"{fit['init']['logE']:.0f}"),
    ]

    mv = load("imgjoint_initE4_mv_front_side")
    out += [
        macro("mvErrE", pct(mv["rel_err_E"])),
        macro("mvErrVz", pct(mv["v0_rel_err"])),
        macro("mvWallMin", f"{mv['wall_time_s'] / 60:.0f}"),
    ]

    sv = load("imgjoint_initE4")
    out += [
        macro("svErrE", pct(sv["rel_err_E"], 0)),
        macro("svBestE", f"{sv['best']['Youngs modulus']:.0f}"),
        macro("svErrVz", pct(sv["v0_rel_err"], 0)),
    ]

    fb = load("imgfield_bend_diag45")
    fm = load("imgfield_mid_side")
    out += [
        macro("fieldBendRelL", f"{fb['v0_field']['rel_l2_best']:.2f}"),
        macro("fieldBendXY", f"{fb['v0_field']['rel_l2_xy_best']:.2f}"),
        macro("fieldMidRelL", f"{fm['v0_field']['rel_l2_best']:.2f}"),
    ]

    mo = load("ours_multiobs/m0_xpym_initE4")
    mo_xp = load("ours_multiobs/m0_xp_initE4")
    out += [
        macro("multiobsErr", pct(mo["rel_err_E"], 3)),
        macro("multiobsSingleErr", pct(mo_xp["rel_err_E"], 3)),
    ]

    # Pillar B: F0 global 6-DOF recovery (warp + finite difference)
    sjson = json.loads((EXPLORE / "f0_train_S/globalS_run/fit_result.json").read_text())
    out += [macro("sErrMax", f"{max(abs(e) for e in sjson['final_err']):.3f}")]

    return "".join(out)


def main() -> None:
    copy_figures()
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    (GEN_DIR / "results.tex").write_text(build_macros())
    print(f"[ok] figures -> {FIG_DIR}")
    print(f"[ok] macros  -> {GEN_DIR / 'results.tex'}")


if __name__ == "__main__":
    main()
